### ISSUE TITLE
Can this be used to run the API as well? 

### ISSUE THREAD

**Issue by spenceralbrecht** [kestr31/docker-stable-diffusion-webui#3]
I'm looking to run the automatic1111 API as a service I can make requests to.

**Comment by kestr31** [comment]
Yes, since this is just a packed container image just as a bare-metal installation, you can use this in API mode.

In order to do so, modify webui-user.sh with api mode COMMANDLINE_ARGS and override it by mapping it on docker-conpose.yml.

**Comment by spenceralbrecht** [comment]
Great, thank you! I appreciate you putting this repo together as I was just going to attempt to containerize this myself. 

I am running it successfully but when I generate images I'm actually getting an error because of a permission issue with the output directory `outputs/txt2img-imges` and the container not being able to write there. Any ideas about how to fix this?

**Comment by kestr31** [comment]
I really appreciate that it helped.

About the permission issue, I think that is caused by unmatching UID-GID settings. You can fix this problem by adding `sudo chown -R user:user /home/user/stable-diffusion-webui/outputs` in `entrypoint.sh` somewhere near the line 30.

If it returns an error, it is might due to a inexistence of that directory. In this case you also seed to state `mkdir /home/user/stable-diffusion-webui/outputs` prior to the modification.

This is an unintended problem. I will fix this problem.

**Comment by spenceralbrecht** [comment]
Okay I'll try that `chown` command and let you know if it works. 

How long should it take for stable-diffusion webui to set up during the build? Mine has been going for about 10 minutes.

![image](https://user-images.githubusercontent.com/15025912/227836713-dbebc9be-aa9a-4da3-8429-0a2245e4a0bb.png)

**Comment by kestr31** [comment]
Yes it really takes a long time. On my PC, it took about 20 minutes. It mainly depends on network speed.

Or, how about trying 1.2.1 image I just uploaded? I fixed that problem so it should work.

**Comment by spenceralbrecht** [comment]
How long did it take you to build? I let mine run for like 35 minutes and
then killed it. Why does it take so long?

**Comment by kestr31** [comment]
About that, I have no idea about is unless I debug it. Sorry that I couldn't help about that problem.
But still, it is fixed on the new image.

**Comment by spenceralbrecht** [comment]
Thank you for fixing the permission issue with the new image! It's working for me. 

I am still having an issue trying to run the API. I don't think the command line arguments from web-user.sh are actually being taken into consideration.  This is the output I'm seeing when the Web UI is starting up. 

`Launching Web UI with arguments: --listen --xformers --skip-torch-cuda-test --styles-file styles/styles.csv --no-download-sd-model --enable-insecure-extension-access`.

I have a `web-user.sh` file with the following contents

![image](https://user-images.githubusercontent.com/15025912/228047299-66ae593f-2865-49c5-861d-f132dbe69d3a.png)

and I am using -v to mount that file on the docker run command.

**Comment by spenceralbrecht** [comment]
I was able to get it working by putting all the arguments I needed in the `webui-user.sh` file because that local file was overwritten all other command line args 

```
export COMMANDLINE_ARGS="--listen \
            --xformers \
            --skip-torch-cuda-test \
            --styles-file styles\/styles.csv \
            --no-download-sd-model \
            --enable-insecure-extension-access \
            --api"
```

**Comment by kestr31** [comment]
Oh I misread it. Yes that part caused a problem because for my case, overriden file I used is longer than the initial setup. Thank you and I will fix this too. I am glad that you could workaround this problem.

**Comment by kestr31** [comment]
I think this issue is fixed for now. Therefore, I'm closing this issue.
